# fly.toml app configuration file generated for llama-worker on 2024-05-06T17:06:42-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'llama-worker'
primary_region = 'ord'
vm.size = 'a100-40gb'

[[mounts]]
source = 'ollama'
destination = '/root/.ollama'
initial_size = '10gb'
