import { Button } from "@/components/ui/button";
import { useStartThread } from "./useStartThread";
import { SignIn } from "./SignIn";
import { Authenticated, Unauthenticated } from "convex/react";

export function EmptyPage() {
  const [startThread, startingThread] = useStartThread();
  return (
    <div className="flex flex-1 flex-col items-center justify-center gap-2">
      <h2 className="text-2xl md:text-4xl">Welcome to llama farm!</h2>
      <p className="p-4 text-center text-lg">
        Start a new conversation with one of the 🦙s on our farm. 🧑‍🌾
        <br />
        Send the link 🔗 of a conversation for friends to join 👯.
      </p>
      <Unauthenticated>
        <SignIn />
      </Unauthenticated>
      <Authenticated>
        <Button
          variant={"default"}
          disabled={startingThread}
          onClick={startThread}
        >
          Start a new conversation
        </Button>
      </Authenticated>
      <pre className="md:mt-16">
        {"💬🧑‍💻-🌐-🧑‍💻💬"}
        <br />
        {"    / \\ "}
        <br />
        {"  | | | | "}
        <br />
        {"  💻💻💻💻 "}
        <br />
        {"  🦙🦙🦙🦙"}
      </pre>
      <p className="max-w-md text-center text-lg">
        All of the responses are generated by <code>llama3</code> running on
        personal computers. <br />
        <span className="p-2 text-sm">
          ...without needing proxied traffic or load balancing, using a
          technique called "work stealing" 🤓
        </span>
        <br />
        <br />
        Use the public farm, or run your own farm to have
        <br />a group chat with friends, augmented with 🦙s.
      </p>
      <a
        href="https://github.com/get-convex/llama-farm-chat"
        className="bg-neutral-n2 text-neutral-n11 hover:bg-neutral-white flex items-center rounded py-4 transition-colors"
        target="_blank"
      >
        <div className="flex grow flex-col">
          <span className="mb-2 text-3xl leading-none">
            get-convex/<strong>llama-farm-chat</strong>
          </span>
        </div>
      </a>
    </div>
  );
}
